markdown: redcarpet

redcarpet:
  extensions: [smart]
pygments: true
permalink: /:title.html

name: computer "scientist"
description: My name is Alex Clemmer, and this is a web site that has not quite gotten me fired yet.
url: http://www.nullspace.io